language: r
sudo: false
cache:
  packages: true
  directories:
  - _cache
git:
  depth: 3
script:
- Rscript -e 'rmarkdown::render_site()'
- git config --global user.name "Ben Best (Travis-CI)"
- git config --global user.email "bdbest@gmail.com"
- git add -A
- git commit -a -m "Updating website via travis-ci.org [ci skip]"
- git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:${TRAVIS_BRANCH}
#after_success:
notifications:
  email:
    recipients:
    - bdbest@gmail.com
    on_success: change
    on_failure: always
env:
  global:
    secure: KTUpgZtIioDdi9WR4YCOeTuxTqcSdGnhfYJggKQ07mJ82uQNqh4712bkugVKAfMs0idtFbTAx3cVuGSGfxm/PsfYFFZc+RCGDAqx0a7dgYhwcEqkPgh/FqlCVgq+e3/5NfjqKJxkg/NSmTts8CfYvFiLoTYCeaFUgO2JliuJHMo1w1W/dizOMHyRRCtvm0b2hZ3n4511kOxwNaJ2vdCJXAC3P849mhjhhE8Bep56RZNXmPcVl+nnWGyY4t9rmETcayRB0wk48GZGLdW1jbyFa3mSEAXmLTDy4sOkJmz2awxvbU0pA/MYF+ZcAAX8bxZA7U2hS9dFUwY58nxV/EcAJJPFkL4k0WrfTHuH+becYNwU1I83L/9xDsIyCm+8+wucjLHp1v9rA5IdNVBfHLHWGCEqE/biUvbw/hY0hHczmJhTfkraWQ2Fksrr+qXkhknwm6g3OBmyAyrDpBRXl+DOovGLGQPa43R4OcB70vA+l0EmbEJmQ0vIUD/cB9bhhaCJKuK5nPNIqs51CWgrzpGwAikefFBYD2tIqi/4X92UXXWMDVDQQvroeuJkrzjFwslVvtX3NaUr2LYgkl9fELmlVMDjqraVdAjqGmYORxK6XYhqJ6rJ73QZ8YkLqH95G4KE+UX7vWxPFLTyf7hZqdl6YMCbea7AIPRquWx4K3+ineI=
